---

- name: "Change the hostname to {{hostname}}"
  win_hostname:
    name: "{{inventory_hostname}}"
  register: win_hostname

- name: Reboot if needed
  win_reboot:
    reboot_timeout: 600
    post_reboot_delay: 100
  when: win_hostname.reboot_required

# Join domain
- name: Set configure dns
  win_dns_client:
    adapter_names: '*'
    ip_addresses:
    - "{{ ip_dc }}"
#    - "{{ ip_dc2 }}"
#    log_path: C:\dns_log.txt

- name: Join machine to domain
  microsoft.ad.membership:
    dns_domain_name: "{{ domain_name }}"
    domain_admin_user: "{{ domain_admin }}@{{ domain_name }}"
    domain_admin_password: "{{ ansible_password }}"
    state: domain
  register: domain_state

- name: Reboot after joining domain
  win_reboot:
  when: domain_state.reboot_required
