---

# Install AD
#- name: Create new AD domain
#  microsoft.ad.domain:
#    dns_domain_name: "{{ domain_name_child }}"
#    within_forest: "{{ domain_name }}"
#    domain_netbios_name: "{{ domain_netbios_name_child }}"
#    safe_mode_password: "{{ random_password_child }}"
#    reboot: true
    
    
- name: Set configure dns
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses: 
    - "{{ ip_dc }}"
#    - "{{ ip_dc2 }}"
   # log_path: C:\dns_log.txt
   
- name: "Change the hostname to {{hostname}}"
  win_hostname:
    name: "{{inventory_hostname}}"
  register: win_hostname
  
- name: Reboot if needed
  win_reboot:
    reboot_timeout: 600
    post_reboot_delay: 100
  when: win_hostname.reboot_required
