---

#- name: Copy desktop wallpaper
#  win_copy:
#    src: DesktopWallpaper.png
#    dest: C:\Users\Public\Pictures\DesktopWallpaper.png

- name: Copy bginfo configuration
  win_copy:
    src: bginfo.bgi
    dest: C:\Users\Public\bginfo.bgi
    
- name: Copy background
  win_copy:
    src: logo.jpg
    dest: C:\Windows\Web\Wallpaper\Windows\
    

- name: Copy bginfo binary
  win_copy:
    src: Bginfo64.exe
    dest: C:\Users\Public\bginfo.exe

- name: Configure bginfo as autorun
  win_regedit:
    path: 'HKCU:\SOFTWARE\Sysinternals'
    name: EulaAccepted
    data: 1

- name: Configure bginfo as autorun
  win_regedit:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run'
    name: bginfo
    data: 'C:\Users\Public\bginfo.exe C:\Users\Public\bginfo.bgi /silent /timer:0 /nolicprompt'


