---
- name: Test
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Fin de pruebas
    shell: rm ejecucion_correcta.txt && touch ejecucion_correcta.txt
    ignore_errors: yes
    
- name: Test
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Fin de pruebas
    shell: touch ejecucion_correcta.txt
